//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDZ.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuctionComments
    {
        public System.Guid CommentID { get; set; }
        public string CommentText { get; set; }
        public System.DateTime CommentTime { get; set; }
        public string CommentAuthor { get; set; }
        public System.Guid AuctionID { get; set; }
        public string AuctionTitle { get; set; }
    }
}
