//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDZ.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bids
    {
        public System.Guid BidID { get; set; }
        public long BidAmount { get; set; }
        public System.DateTime BidTime { get; set; }
        public System.Guid UserID { get; set; }
        public System.Guid AuctionID { get; set; }
    
        public virtual Auctions Auctions { get; set; }
        public virtual Users Users { get; set; }
    }
}
